import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Boiler plate </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <p>This is the main content</p>
    </>
  );
}
